import Main from '../../components/Main'
import Head from 'next/head'
import Navbar from '../../components/Navbar'
import About from '../../components/About'
import Skills from '../../components/Skills'
import Projects from '../../components/Projects'
import Contact from '../../components/Contact'

export default function Home() {
  return (
    <>
      <Head>
        <title>Collins Rotich | Cloud native Engineer</title>
        <meta name="google-site-verification" content="zh639jOGtqKYkJdt6pzwPHZCUsmsqiATUyCUGSnI42M" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/iotlogo.png" />
      </Head>
      
      <Main />
      <About />
      <Skills />
      <Projects />
      <Contact />
    </>
  )
}
